[yolov2-COCO]
git-tree-sha1 = "c5f4d31e5c9c5d6fba7469ceff3d9916050d92d2"
lazy = true

    [[yolov2-COCO.download]]
    sha256 = "2aea399ab3c6b6e3a4285ec6ae31b858803442bf1b3e3e4889a2e3e8287d56c6"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov2-COCO.tar.gz"

[yolov2-tiny-COCO]
git-tree-sha1 = "938cb0829a7a92b650e4552042a6ba45de542dc8"
lazy = true

    [[yolov2-tiny-COCO.download]]
    sha256 = "5c9003093b0a2d8a1c77f2d46c64f6fe994438b98beffe1db65ed02e48d31df3"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov2-tiny-COCO.tar.gz"

[yolov3-COCO]
git-tree-sha1 = "9c3cfcb6f671eeec6efd9b1f87d6dd33a5373ec3"
lazy = true

    [[yolov3-COCO.download]]
    sha256 = "346ff78dd0608a2fe6c98414e2cbee0a99c5026dc3cd750eb7333e3adc105259"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov3-COCO.tar.gz"

[yolov3-spp-COCO]
git-tree-sha1 = "c65c83be12182eb27ed883d2f165fa6b6b704616"
lazy = true

    [[yolov3-spp-COCO.download]]
    sha256 = "deeb38b02b635b344bc9a154ced589678ccaa6e39e3c4f71eec0068cc77ac548"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov3-spp-COCO.tar.gz"

[yolov3-tiny-COCO]
git-tree-sha1 = "dea5741f967df8650dfca0ee7f6ac70fc4a9898b"
lazy = true

    [[yolov3-tiny-COCO.download]]
    sha256 = "64af28810b9bb2d02f2b0fdc783457dc15f9ed2d455af75062ffeaa4d69f1092"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov3-tiny-COCO.tar.gz"

[yolov4-COCO]
git-tree-sha1 = "3c641b432896e5b3a136e0fe36e4dc6d635c80dd"
lazy = true

    [[yolov4-COCO.download]]
    sha256 = "9e8ef718f074b15bf8b49b1750764a737367ba08a2422ea51fc67e687bba9c98"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights2/yolov4-COCO.tar.gz"

[yolov4-csp-COCO]
git-tree-sha1 = "0ed4c06e067b130a78eab84aaff62621f9b08282"
lazy = true

    [[yolov4-csp-COCO.download]]
    sha256 = "e6a6ce7551b94b3ff4f493e19670c16a1c766578b16e56d2008c6cfc7c8bec02"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov4-csp-COCO.tar.gz"

[yolov4-csp-x-swish-COCO]
git-tree-sha1 = "842cc97e64259829d7c23398ae135ab8e4fa58f1"
lazy = true

    [[yolov4-csp-x-swish-COCO.download]]
    sha256 = "8a6c602e6c6c862ba82980c9552339fc665fc11943a4536df6456009472ededa"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov4-csp-x-swish-COCO.tar.gz"

[yolov4-p5-COCO]
git-tree-sha1 = "9d783cbaf16302afb118956b79491b23553e71f2"
lazy = true

    [[yolov4-p5-COCO.download]]
    sha256 = "3c158eafa4719f0e502bbc5f710084d470b6af32c6fee59344c625b450acee79"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov4-p5-COCO.tar.gz"

[yolov4-p6-COCO]
git-tree-sha1 = "cdee6a06e053e68aa606e5761312667ac778a8d5"
lazy = true

    [[yolov4-p6-COCO.download]]
    sha256 = "7ae1725e5b0d11ee09ef4cc40dcd4e8a7223302a42d3802df0ec28e46a235e3d"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov4-p6-COCO.tar.gz"

[yolov4-tiny-COCO]
git-tree-sha1 = "ddad97b7d60da0cffd2b12003a5c42e88fcaedae"
lazy = true

    [[yolov4-tiny-COCO.download]]
    sha256 = "6e96d427f769d2dd2f1aadf96f6b8d8e8e19fc5a6e8e81ffa4dc8bda9c7d6ea3"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights2/yolov4-tiny-COCO.tar.gz"

[yolov4x-mish-COCO]
git-tree-sha1 = "b04bfb646371d6e2eefd737b4154bca45b096ccd"
lazy = true

    [[yolov4x-mish-COCO.download]]
    sha256 = "3bdd747199ddf911af9f65ea3aae9f361ee17835803ca110357e0c7160f8f685"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov4x-mish-COCO.tar.gz"

[yolov7-COCO]
git-tree-sha1 = "817fb08f81f72429d84a08d552d54d8195d937de"
lazy = true

    [[yolov7-COCO.download]]
    sha256 = "dfe41e9513aa3bd48399526ad41229d518114013df26f9da30643b092a2fd9c2"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights2/yolov7-COCO.tar.gz"

[yolov7-tiny-COCO]
git-tree-sha1 = "aa0903f7cc14302bdc3e032c7c77843e60577521"
lazy = true

    [[yolov7-tiny-COCO.download]]
    sha256 = "d46863dfebb4b6008eb91f291ba59281bfd6d256c828a33b825969695abcea1a"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights2/yolov7-tiny-COCO.tar.gz"

[yolov7x-COCO]
git-tree-sha1 = "57a1c0aa23f2bf5ef80d46f1eeb965ccedfc61f5"
lazy = true

    [[yolov7x-COCO.download]]
    sha256 = "1acd8798e8eaa4836c403501315084ba0a0d9f107355506186ed295a249bebac"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov7x-COCO.tar.gz"
