[yolov2-COCO]
git-tree-sha1 = "c5f4d31e5c9c5d6fba7469ceff3d9916050d92d2"
lazy = true

    [[yolov2-COCO.download]]
    sha256 = "2aea399ab3c6b6e3a4285ec6ae31b858803442bf1b3e3e4889a2e3e8287d56c6"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov2-COCO.tar.gz"

[yolov2-tiny-COCO]
git-tree-sha1 = "938cb0829a7a92b650e4552042a6ba45de542dc8"
lazy = true

    [[yolov2-tiny-COCO.download]]
    sha256 = "5c9003093b0a2d8a1c77f2d46c64f6fe994438b98beffe1db65ed02e48d31df3"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov2-tiny-COCO.tar.gz"

[yolov3-COCO]
git-tree-sha1 = "9c3cfcb6f671eeec6efd9b1f87d6dd33a5373ec3"
lazy = true

    [[yolov3-COCO.download]]
    sha256 = "346ff78dd0608a2fe6c98414e2cbee0a99c5026dc3cd750eb7333e3adc105259"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov3-COCO.tar.gz"

[yolov3-spp-COCO]
git-tree-sha1 = "c65c83be12182eb27ed883d2f165fa6b6b704616"
lazy = true

    [[yolov3-spp-COCO.download]]
    sha256 = "deeb38b02b635b344bc9a154ced589678ccaa6e39e3c4f71eec0068cc77ac548"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov3-spp-COCO.tar.gz"

[yolov3-tiny-COCO]
git-tree-sha1 = "dea5741f967df8650dfca0ee7f6ac70fc4a9898b"
lazy = true

    [[yolov3-tiny-COCO.download]]
    sha256 = "64af28810b9bb2d02f2b0fdc783457dc15f9ed2d455af75062ffeaa4d69f1092"
    url = "https://github.com/r3tex/ObjectDetector.jl/releases/download/weights/yolov3-tiny-COCO.tar.gz"
